[package]
name = "quadratic_sieve"
version = "0.1.0"
authors = ["Evan Severson <severson.evan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-gmp = "0.5.0"
